server:
  port: 8888

spring:
  application:
    name: local-client

grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9899'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
